### ISSUE TITLE
Ipopt.exe doesn't run on Windows/Julia 0.7

### ISSUE THREAD

**Issue by mlubin** [jump-dev/Ipopt.jl#119]
```
C API: Test Failed at C:\Users\Miles\.julia\dev\Ipopt\test\runtests.jl:28
  Expression: success(#= C:\Users\Miles\.julia\dev\Ipopt\test\runtests.jl:28 =# @cmd("\$(Ipopt.amplexe) -v"))
```

Recall that the exe has weird dependencies on the libraries that are only available when running Julia: https://github.com/JuliaOpt/Ipopt.jl/blob/3da72b6f51a78bb0daf049a9bef12c57944841a0/src/Ipopt.jl#L23

So something along these lines probably changed between 0.6 and 0.7

@staticfloat

**Comment by odow** [comment]
I can't reproduce this. I went

```julia
(v0.7) pkg> add Ipopt#Master
```

```
julia> run(@cmd("\$(Ipopt.amplexe) -v"))
Ipopt 3.12.8 (Windows ), ASL(20160307)
Process(`'C:\Users\Oscar\.julia\packages\Ipopt\0MSc\deps\usr\bin\ipopt.exe' -v`, ProcessExited(0))

julia> versioninfo()
Julia Version 0.7.0-alpha.126
Commit 0e4493d598* (2018-06-14 13:46 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-3537U CPU @ 2.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, ivybridge)
```

Tests pass as well.

**Comment by staticfloat** [comment]
Unfortunately, I don't have easy access to a windows computer to test this out right now.  Is there an error message that you can see that comes from trying to call `run()`?

**Comment by mlubin** [comment]
The error message doesn't seem to useful to me. I can reproduce the issue locally, and it also happens on AppVeyor (https://ci.appveyor.com/project/JuliaOpt/ipopt-jl/build/1.0.48/job/v03cmrbup7r3jits#L193). 
```
julia> run(`$(Ipopt.amplexe) -v`)
ERROR: failed process: Process(`'C:\Users\Miles\.julia\dev\Ipopt\deps\usr\bin\ipopt.exe' -v`, ProcessExited(3221225781)) [3221225781]
Stacktrace:
 [1] error(::String, ::Base.Process, ::String, ::Int64, ::String) at .\error.jl:42
 [2] pipeline_error at .\process.jl:712 [inlined]
 [3] #run#511(::Bool, ::Function, ::Cmd) at .\process.jl:670
 [4] run(::Cmd) at .\process.jl:668
 [5] top-level scope

julia> versioninfo()
Julia Version 0.7.0-alpha.0
Commit 22590d529d* (2018-05-31 00:07 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)
```

**Comment by staticfloat** [comment]
That is helpful though!  Error 3221225781 is STATUS_DLL_NOT_FOUND.  So your suspicions are correct, it's unable to find certain .DLLs.  I'm not sure what it could be missing, however.  Here's the dependency chain, as I am able to determine:

```julia
julia> using ObjectFile

julia> get_deps(filename) = [path(dl) for dl in DynamicLinks(readmeta(filename))]
get_deps (generic function with 1 method)

julia> get_deps("ipopt.exe")
WARNING: `readmeta(file::AbstractString)` is deprecated, use the do-block variant instead.
6-element Array{String,1}:
 "libipoptamplinterface-1.dll"
 "libstdc++-6.dll"
 "libgcc_s_seh-1.dll"
 "KERNEL32.dll"
 "msvcrt.dll"
 "libipopt-1.dll"

julia> function recursive_missing_deps_search(filename)
           missing_deps = []
           for dep in get_deps(filename)
               if !isfile(dep)
                   push!(missing_deps, dep)
               else
                   append!(missing_deps, recursive_missing_deps_search(dep))
               end
           end
           return unique(missing_deps)
       end
recursive_missing_deps_search (generic function with 1 method)

julia> recursive_missing_deps_search("ipopt.exe")
... snip warnings ...
5-element Array{String,1}:
 "libgcc_s_seh-1.dll"
 "KERNEL32.dll"
 "msvcrt.dll"
 "libstdc++-6.dll"
 "libgfortran-3.dll"
```

This shows to me that these are the only 5 libraries missing from this current directory, and all of these should be available within Julia's `bin` directory.  That directory will, of course, have to be on your `PATH` variable for them to be found by the dynamic linker when running Julia.  Perhaps try something like:

```julia
julia_bindir = Base.JULIA_HOME
pathsep = iswindows() ? ';' : ':'
new_path = "$(julia_bindir)$(pathsep)$(ENV["PATH"])"
withenv("PATH" => new_path) do
    run(`$(Ipopt.amplexe) -v`)
end
```

**Comment by linzgood** [comment]
![1](https://user-images.githubusercontent.com/10878749/98462680-06cf0e80-21f1-11eb-8bf9-96352411327d.PNG)
![Uploading 2.PNG…]()

**Comment by linzgood** [comment]
![Uploading 1.PNG…]()

**Comment by staticfloat** [comment]
@linzgood it looks to me like you might be using a very old version of Julia; what version are you using?

**Comment by mlubin** [comment]
I'm closing this issue because it's stale. We no longer support Julia 0.7, and the procedure for generating the Ipopt binaries has changed substantially.

@linzgood Please use Julia 1.0 or greater, and post on https://discourse.julialang.org/ if you continue to have issues.
