### ISSUE TITLE
Don't use reference BLAS

### ISSUE THREAD

**Issue by andreasnoack** [jump-dev/Ipopt.jl#128]
It looks like the Ipopt builds and links to some version of reference BLAS, https://travis-ci.org/JuliaOpt/Ipopt.jl/jobs/406796051#L621-L637.

Also, the restrictions mentioned in https://github.com/JuliaOpt/Ipopt.jl/blob/870f037abc69c5cbc063b263e8960fe6c41c58f6/deps/build.jl#L8 no longer apply.

Update: I linked to the wrong line in the first version

**Comment by odow** [comment]
Closed by #153 and Ipopt_jll.
