### ISSUE TITLE
getobjbound and getsolvetime

### ISSUE THREAD

**Issue by ccoffrin** [jump-dev/Ipopt.jl#148]
It would be good to implement `getobjbound` and `getsolvetime` on this wrapper and the MOI analogs.  These are likely needed for hybrid solvers, e.g. see https://github.com/mlubin/ConicNonlinearBridge.jl/pull/15

**Comment by odow** [comment]
Closing since https://github.com/jump-dev/Ipopt.jl/pull/235 adds a test for `MOI.SolveTime`, and I'm not aware of any functionality for `MOI.ObjectiveBound` in Ipopt.

**Comment by ccoffrin** [comment]
I can confirm MOI updates have addressed this issue.
