### ISSUE TITLE
Error building 'Ipopt' when compiled to use with MKL Pardiso Solver

### ISSUE THREAD

**Issue by ollamc** [jump-dev/Ipopt.jl#195]
I am trying to use the MKL Pardiso solver with Ipopt. Therefore I compile Ipopt from source according to the documentation (https://coin-or.github.io/Ipopt/INSTALL.html#EXTERNALCODE_LINALG):
`./configure --with-lapack="-L${MKLROOT}/lib/intel64 -Wl,--no-as-needed -lmkl_intel_lp64 -lmkl_sequential -lmkl_core -lm"`
Everyting seems to compile properly, and the make test is passed.

I then use the environmental variables `JULIA_IPOPT_LIBRARY_PATH = "/build/lib"` and `JULIA_IPOPT_EXECUTABLE_PATH = "/build/lib"` to point at my custom installation (`/build` is where I compile Ipopt).

When I build Ipopt, through `Pkg.build("Ipopt")`, I get the following error:

```
Error: Error building `Ipopt`: 
│ ERROR: LoadError: Could not install custom libraries from /build/lib and /build/bin.
│ To fall back to BinaryProvider call delete!(ENV,"JULIA_IPOPT_LIBRARY_PATH");delete!(ENV,"JULIA_IPOPT_EXECUTABLE_PATH") and run build again.
│ Stacktrace:
│  [1] error(::String) at ./error.jl:33
│  [2] top-level scope at /home/olivier/.julia/packages/Ipopt/ruIXY/deps/build.jl:63
│  [3] include at ./boot.jl:317 [inlined]
│  [4] include_relative(::Module, ::String) at ./loading.jl:1044
│  [5] include(::Module, ::String) at ./sysimg.jl:29
│  [6] include(::String) at ./client.jl:392
│  [7] top-level scope at none:0
│ in expression starting at /home/olivier/.julia/packages/Ipopt/ruIXY/deps/build.jl:57
└ @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1096
```

If I simply compile without any flag with  `./configure`, Julia is able to compile Ipopt from the same environmental variables.

I am also able to use the solver through Pardiso.jl with `MKLPardisoSolver()`.

I am using Julia 1.0.5 on Ubuntu 18.04.4.

Thank you

**Comment by blegat** [comment]
Can you give the output with `--verbose` (use the latest BinaryProvider, it gives more output)

**Comment by ollamc** [comment]
I'm sorry but I cant figure out what you mean by "Give the output with `--verbose`". Could you give me more information?

By the way I'm only a beginner on Julia...

**Comment by blegat** [comment]
Run
```julia
$ JULIA_IPOPT_LIBRARY_PATH="/build/lib" JULIA_IPOPT_EXECUTABLE_PATH="/build/lib" julia /home/olivier/.julia/packages/Ipopt/ruIXY/deps/build.jl --verbose
```

**Comment by ollamc** [comment]
Here is the output: 
`[ Info: Found a valid dl path libipopt.so while looking for libipopt

[ Info: /home/olivier/build/lib/libipopt.so matches our search criteria of libipopt
┌ Info: /home/olivier/build/lib/libipopt.so cannot be dlopen'ed
│   dlopen_result =
│    could not load library "/home/olivier/build/lib/libipopt.so"
└    /home/olivier/build/lib/libipopt.so: wrong ELF class: ELFCLASS64
[ Info: Found a valid dl path libipopt.so.3 while looking for libipopt
[ Info: /home/olivier/build/lib/libipopt.so.3 matches our search criteria of libipopt
┌ Info: /home/olivier/build/lib/libipopt.so.3 cannot be dlopen'ed
│   dlopen_result =
│    could not load library "/home/olivier/build/lib/libipopt.so.3"
└    /home/olivier/build/lib/libipopt.so.3: wrong ELF class: ELFCLASS64
[ Info: Found a valid dl path libipopt.so.3.13.3 while looking for libipopt
[ Info: /home/olivier/build/lib/libipopt.so.3.13.3 matches our search criteria of libipopt
┌ Info: /home/olivier/build/lib/libipopt.so.3.13.3 cannot be dlopen'ed
│   dlopen_result =
│    could not load library "/home/olivier/build/lib/libipopt.so.3.13.3"
└    /home/olivier/build/lib/libipopt.so.3.13.3: wrong ELF class: ELFCLASS64
[ Info: Found a valid dl path libipoptamplinterface.so while looking for libipopt
[ Info: /home/olivier/build/lib/libipoptamplinterface.so matches our search criteria of libipopt
┌ Info: /home/olivier/build/lib/libipoptamplinterface.so cannot be dlopen'ed
│   dlopen_result =
│    could not load library "/home/olivier/build/lib/libipoptamplinterface.so"
└    /home/olivier/build/lib/libipoptamplinterface.so: wrong ELF class: ELFCLASS64
[ Info: Found a valid dl path libipoptamplinterface.so.3 while looking for libipopt
[ Info: /home/olivier/build/lib/libipoptamplinterface.so.3 matches our search criteria of libipopt
┌ Info: /home/olivier/build/lib/libipoptamplinterface.so.3 cannot be dlopen'ed
│   dlopen_result =
│    could not load library "/home/olivier/build/lib/libipoptamplinterface.so.3"
└    /home/olivier/build/lib/libipoptamplinterface.so.3: wrong ELF class: ELFCLASS64
[ Info: Found a valid dl path libipoptamplinterface.so.3.13.3 while looking for libipopt
[ Info: /home/olivier/build/lib/libipoptamplinterface.so.3.13.3 matches our search criteria of libipopt
┌ Info: /home/olivier/build/lib/libipoptamplinterface.so.3.13.3 cannot be dlopen'ed
│   dlopen_result =
│    could not load library "/home/olivier/build/lib/libipoptamplinterface.so.3.13.3"
└    /home/olivier/build/lib/libipoptamplinterface.so.3.13.3: wrong ELF class: ELFCLASS64
[ Info: Found a valid dl path libsipopt.so while looking for libipopt
[ Info: Found a valid dl path libsipopt.so.3 while looking for libipopt
[ Info: Found a valid dl path libsipopt.so.3.13.3 while looking for libipopt
[ Info: Could not locate libipopt inside /home/olivier/build/lib
ERROR: LoadError: Could not install custom libraries from /home/olivier/build/lib and /home/olivier/build/bin.
To fall back to BinaryProvider call delete!(ENV,"JULIA_IPOPT_LIBRARY_PATH");delete!(ENV,"JULIA_IPOPT_EXECUTABLE_PATH") and run build again.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] top-level scope at /home/olivier/.julia/packages/Ipopt/ruIXY/deps/build.jl:63
 [3] include at ./boot.jl:317 [inlined]
 [4] include_relative(::Module, ::String) at ./loading.jl:1044
 [5] include(::Module, ::String) at ./sysimg.jl:29
 [6] exec_options(::Base.JLOptions) at ./client.jl:266
 [7] _start() at ./client.jl:425
in expression starting at /home/olivier/.julia/packages/Ipopt/ruIXY/deps/build.jl:57
`

**Comment by blegat** [comment]
Could you give the output of `file /home/olivier/build/lib/libipopt.so.3.13.3` and `ldd /home/olivier/build/lib/libipopt.so.3.13.3` ? Where is the MKL library ? Is it 32-bit or 64-bit ? Is it linked statically or dynamically with `libipopt.so.3.13.3` ?

**Comment by ollamc** [comment]
Output of `file /home/olivier/build/lib/libipopt.so.3.13.3`:
`/home/olivier/build/lib/libipopt.so.3.13.3: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=ee1379c6b915d9d7c40e452a373f4aae6e0787af, not stripped`

Output of `ldd /home/olivier/build/lib/libipopt.so.3.13.3`:
```
linux-vdso.so.1 (0x00007ffceadd1000)
	libmkl_intel_lp64.so => /home/olivier/intel/compilers_and_libraries_2020.1.217/linux/mkl/lib/intel64_lin/libmkl_intel_lp64.so (0x00007f3be5982000)
	libmkl_sequential.so => /home/olivier/intel/compilers_and_libraries_2020.1.217/linux/mkl/lib/intel64_lin/libmkl_sequential.so (0x00007f3be435b000)
	libmkl_core.so => /home/olivier/intel/compilers_and_libraries_2020.1.217/linux/mkl/lib/intel64_lin/libmkl_core.so (0x00007f3bdffdb000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f3bdfdd7000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f3bdfa4e000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f3bdf6b0000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f3bdf2bf000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f3be6920000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f3bdf0a7000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f3bdee88000)
```

The MKL library is at `/home/olivier/intel/compilers_and_libraries_2020.1.217/linux/mkl`

It is 64-bit.

It seems to be dynamically linked by default.

**Comment by ollamc** [comment]
I fixed the problem updating to julia v.1.4.1.

I am now able to build Ipopt with MKL Pardiso. 

I now run in a new problem which is the following error:
```
INTEL MKL ERROR: /home/olivier/intel/compilers_and_libraries_2020.1.217/linux/mkl/lib/intel64_lin/libmkl_avx2.so: undefined symbol: mkl_sparse_optimize_bsr_trsm_i8.
Intel MKL FATAL ERROR: Cannot load libmkl_avx2.so or libmkl_def.so.
```

This happens inside of Ipopt as the following shows:
```
******************************************************************************
This program contains Ipopt, a library for large-scale nonlinear optimization.
 Ipopt is released as open source code under the Eclipse Public License (EPL).
         For more information visit http://projects.coin-or.org/Ipopt
******************************************************************************

This is Ipopt version 3.13.3, running with linear solver pardiso.

Number of nonzeros in equality constraint Jacobian...:        0
Number of nonzeros in inequality constraint Jacobian.:        0
Number of nonzeros in Lagrangian Hessian.............:   270499

Total number of variables............................:    19509
                     variables with only lower bounds:        0
                variables with lower and upper bounds:     6524
                     variables with only upper bounds:        0
Total number of equality constraints.................:        0
Total number of inequality constraints...............:        0
        inequality constraints with only lower bounds:        0
   inequality constraints with lower and upper bounds:        0
        inequality constraints with only upper bounds:        0

iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
   0  1.2104357e-01 0.00e+00 7.16e+01  -8.0 0.00e+00    -  0.00e+00 0.00e+00   0
INTEL MKL ERROR: /home/olivier/intel/compilers_and_libraries_2020.1.217/linux/mkl/lib/intel64_lin/libmkl_avx2.so: undefined symbol: mkl_sparse_optimize_bsr_trsm_i8.
Intel MKL FATAL ERROR: Cannot load libmkl_avx2.so or libmkl_def.so.
```

**Comment by svigerske** [comment]
The last problem (MKL not finding its own functions) is something I also get when trying to use the Java interface of Ipopt (https://github.com/coin-or/Ipopt/blob/stable/3.14/src/Interfaces/Ipopt.java#L210-L217). Java loads the Ipopt library at runtime. Since Ipopt has been build against MKL, it also loads the MKL libs, for example libmkl_sequential.so (which defines `mkl_sparse_optimize_bsr_trsm_i8`). But Java loads the Ipopt lib with RTLD_LOCAL, so that functions loaded at this time are not available for libraries that are loaded in the future. When MKL then runs and tries to load `libmkl_avx2.so`, this fails because of (implicit) dependencies of `libmkl_avx2.so` onto other MKL libs.

**Comment by odow** [comment]
You could try explicitly loading the MKL libraries using RTLD_LOCAL before Ipopt. So something like:
```Julia
import Libdl
Libdl.dlopen("/home/olivier/intel/compilers_and_libraries_2020.1.217/linux/mkl/lib/intel64_lin/libmkl_core.so", RTLD_GLOBAL)
using JuMP, Ipopt
# ...
```
I don't know if I got the filename right, and there might be other libraries you need to open. (I don't have MKL so I can't test.)

I'll leave this issue open for a while, but if there is no progress I will close. This isn't an issue with Ipopt.jl. If you have installation instructions that work let me know, https://github.com/jump-dev/Ipopt.jl/issues/247, and I will add them to the documentation.

**Comment by odow** [comment]
Instead of the `JULIA_IPOPT_LIBRARY_PATH` approach, you can also try the instructions for using a custom binary: https://jump.dev/JuMP.jl/dev/developers/custom_solver_binaries/

Closing because this isn't a bug in Ipopt.jl. If you find working instructions, please post them in #247.
