### ISSUE TITLE
Linear Solver kwarg interface 

### ISSUE THREAD

**Issue by jd-lara** [jump-dev/Ipopt.jl#201]
A recent conversation with @staticfloat in Slack lead to a discussion about Ipopt's interface to set the linear solver as an attribute instead of using a custom version of Ipopt that has been compiled with the specific linear solver of interest. 

Upon looking at the code to load the linear solvers in Ipopt https://github.com/coin-or/Ipopt/blob/d16c8fb5785d5524a489a7192d90440af29d55d2/src/contrib/LinearSolverLoader/LibraryHandler.c it seems like they load the library directly based on the name, for instance `libpardiso.dylib`. 

This behavior can be problematic if one wants to use the Paradiso version in `MKL_jll` or if the linear solver library can't be found in the system's environment. For example, this can happen in MacOS if the SIP blocks forwarding DYLD_LIBRARY_PATH or in recent OS versions that removed `/usr/local/lib` from the default DYLD_LIBRARY_PATH. 

A suggestion from @staticfloat is to do a ccall when loading the linear solver libraries and manually calling something along the lines of `LSL_loadPardiso("@rpath/libpardiso.dylib", msgbuf, msglen)` such that the next time that the dynamic library is called for the solve Ipopt uses the one loaded already. 

The option could be also to add within addOption(), look for the kwarg `linearsolver`, and pattern match the ccall that looks for the library using @rpath or alternatively call for all the possible solvers at the load time.

**Comment by jd-lara** [comment]
More details are in this thread in slack https://julialang.slack.com/archives/C674ELDNX/p1590776964415600

**Comment by odow** [comment]
#236 gives instructions for how to use `linear_solver` on a number of platforms and different solvers.

**Comment by svigerske** [comment]
Ipopt 3.14 (currently beta) introduces an option to set the name and path of the pardiso library to be loaded at runtime and has the library loading mechanism reimplemented (e.g., `LSL_loadPardiso` is gone): https://github.com/coin-or/Ipopt/releases

For the HSL routines, there is also a (C++) API call to set pointers to these functions if you have them already, e.g.,
https://github.com/coin-or/Ipopt/blob/stable/3.14/src/Algorithm/LinearSolvers/IpMa27TSolverInterface.hpp#L141-L148
I will just add such a function also for Pardiso from pardiso-project.

**Comment by odow** [comment]
The new `hsllib` and `pardisolib` options are great: https://coin-or.github.io/Ipopt/OPTIONS.html (thanks @svigerske).

I also wrote some docs on how to more easily use a custom library: https://jump.dev/JuMP.jl/dev/developers/custom_solver_binaries/

So I'm going to close this as won't fix.
