### ISSUE TITLE
Invalid model when constraint or objective involves term of decision variables such as x^a, where a is between (1, 2)

### ISSUE THREAD

**Issue by YuWVandy** [jump-dev/Ipopt.jl#206]
Hi guys, recently I'm trying to solve a large nonlinear optimization problem and the termination status keeps showing me "INVALID_MODEL" and I have simplified it into the following problem:

using Juniper
using Ipopt
using JuMP

optimizer = Juniper.Optimizer
nl_solver = optimizer_with_attributes(Ipopt.Optimizer, "print_level"=>0)
using LinearAlgebra # for the dot product
model = Model(optimizer_with_attributes(optimizer, "nl_solver"=>nl_solver))

@variable(model, x, start = 0.0)
@variable(model, y, start = 0.0)
@NLconstraint(model, x + y^a== 10)

@NLobjective(model, Min, (1 - x)^2 + 100 * (y - x^2)^2)

optimize!(model)
println("x = ", value(x), " y = ", value(y))

It turns out as long as I set the value of a between 1 and 2, then the return status of the model is "INVALID_MODEL". Does anyone have any idea of it?

**Comment by odow** [comment]
Ipopt requires that all problems are twice differentiable. The derivative of the first constraint has `a * y^(a - 1)`. When `a = 1.5` (for example), this is a square root which is undefined at `y = 0` (your starting point).

Just add a non-zero lower bound to `y`: `@variable(model, y >= 0.0001)`.

**Comment by YuWVandy** [comment]
> Ipopt requires that all problems are twice differentiable. The derivative of the first constraint has `a * y^(a - 1)`. When `a = 1.5` (for example), this is a square root which is undefined at `y = 0` (your starting point).
> 
> Just add a non-zero lower bound to `y`: `@variable(model, y >= 0.0001)`.

Thanks odow! That perfectly solves my problem here. The other way I can think about is to perform a simple transformation of the constraint 'x + y^a == 10' to 'y^a == 10 - x', then square both sides. But this is not a general way. Yours is more applicable!
