### ISSUE TITLE
Reason for the problem "INVALID MODEL"

### ISSUE THREAD

**Issue by YuWVandy** [jump-dev/Ipopt.jl#207]
Recently, when I use IPOPT to solve a large nonlinear optimization problem, when I add some constraints, the result keeps showing me the model is invalid. The document on the juMP website tells us there is some problem with such optimization but doesn't attach many details. The raw code for this problem is very complex so I do not post it here but has anyone been experienced with this problem or has some draft ideas? Thanks!

**Comment by odow** [comment]
Same answer as my comment yesterday: https://github.com/jump-dev/Ipopt.jl/issues/206#issuecomment-650165474

You are probably violating the assumptions of Ipopt (e.g., you have a derivative that is undefined).

In general, it is impossible to provide advice without the code. If you can't debug the problem, I suggest you form a minimal working example and post to the discourse forum: https://discourse.julialang.org/c/domain/opt/13.

We try to reserve the Github issues for bug reports in Ipopt.jl.

**Comment by YuWVandy** [comment]
Thanks for the answer. I've rechecked my code and the reason I think is in some cases, there is zero appears in the denominator.

**Comment by odow** [comment]
Pleased you got it sorted.
