### ISSUE TITLE
building documentation

### ISSUE THREAD

**Issue by jacobsca** [jump-dev/Ipopt.jl#21]
I am trying to build the documentation on a Mac OS X.

I get the following:

make: **\* No rule to make target `stdlib/*.rst', needed by`helpdb.jl'.  Stop.

Not clear what to do - any help here?

**Comment by mlubin** [comment]
I'm not able to look into this in the next few days, but the documentation could use some updating and reformatting. In the meantime it's available at [ReadTheDocs](http://ipoptjl.readthedocs.org/en/latest/ipopt.html). We also now discourage use of the Ipopt-specific API in favor of the [MathProgBase](http://mathprogbasejl.readthedocs.org/en/latest/nlp.html) interface which is solver independent.
