### ISSUE TITLE
v0.6.2 does not work with user-installed Ipopt

### ISSUE THREAD

**Issue by iaravena** [jump-dev/Ipopt.jl#212]
As indicated in the title, with version [v0.6.2](https://github.com/jump-dev/Ipopt.jl/tree/v0.6.2)
```
ENV["JULIA_IPOPT_LIBRARY_PATH"] = "/path/to/ipopt/lib"
ENV["JULIA_IPOPT_EXECUTABLE_PATH"] = "/path/to/ipopt/bin"
import Pkg; Pkg.build("Ipopt")
```
does not correctly links to user-compiled Ipopt (v3.12.13), `Pkg.build("Ipopt")` returns `false`, and tests continue to call Ipopt version from BinaryProvider.
Same sequence of commands in [v0.6.1](https://github.com/jump-dev/Ipopt.jl/tree/v0.6.1) works without problems.

**Comment by odow** [comment]
You need to ensure that the environment variables continue to be set: https://github.com/jump-dev/Ipopt.jl/blob/50560a34047e34ae792dbf0b9c7d2f87b9ea959a/src/Ipopt.jl#L5

**Comment by iaravena** [comment]
I see. Used a different Ipopt version and it worked. Then, checked `deps.jl` and it seems to be created fine in v0.6.2, even for the version of Ipopt that was causing the problem. Will close for now, as the error may lie somewhere else. Thanks @odow!

**Comment by iaravena** [comment]
@odow, looking back into this, I understand your response better now, nevertheless this seems more of a hack than a solution. Can we check for something else? It is not practical to define environment variables every time we plan on loading the module, these variables are not used anywhere else, the paths to Ipopt stay hardcoded in `deps.jl`.

**Comment by iaravena** [comment]
You can certainly set environment variables, but in this case that would be misleading. Assume that you have multiple Ipopt versions or that you move Ipopt and you update the environment variables accordingly. In such case, Ipopt.jl would not change the library its using, yet it will check that the environment variables exist, but will do nothing with them. Maybe add a warning in deps.jl that checks whether the variables defined match what is installed, if it has been decided to use environment variables for this, otherwise, why not leave a flag in deps.jl indicating that we are using a custom built?

**Comment by iaravena** [comment]
Just to make sure we are on the same page for a PR, do you mean:
1. a flag indicating that we built `Ipopt.jl` with some custom version? or,
2. a check for the environment variables with a warning when they are different from the version used to build `Ipopt.jl`?

**Comment by etatara** [comment]
I had a similar experience with Julia 1.4 and 0.6.3 not finding my Ipopt 3.12.13 binaries.  I've followed the correct procedure JULIA_IPOPT_LIBRARY_PATH as I've done many times in the past.  When creating a new Julia installation in linux, trying to use the HSL solvers via Ipopt would crash Julia and report that it could not load "libhsl.so" which is odd since the binary is libcoinhsl-1.so and correctly specified in the deps.jl.  If I pin Ipopt to 0.6.1 it works fine without any other changes.

**Comment by odow** [comment]
I have updated the documentation to clarify you need both the library and the executable. It also contains instructions on how to use HSL:
https://github.com/jump-dev/Ipopt.jl/tree/od/pardiso#custom-installation

**Comment by odow** [comment]
Closing because #236 now has better instructions for installing custom installations, and for using linear solvers such as HSL, including the `libhsl`/`libcoinhsl` issue.
