### ISSUE TITLE
Trying to load MA97 when HSL is not available crashes Julia

### ISSUE THREAD

**Issue by pjssilva** [jump-dev/Ipopt.jl#213]
Hi,

I am trying to use the following code to identify if MA97 is available and if not use mumps:
```julia
"""
    best_linear_solver

    Helper function to check what is the best linear solver available for Ipopt, 
        ma97 (preferred) or mumps.
"""
function best_linear_solver()
    PREFERRED = "ma97"
    m = Model(optimizer_with_attributes(Ipopt.Optimizer,
              "print_level" => 0, "linear_solver" => PREFERRED))
    @variable(m, x)
    @objective(m, Min, x^2)
    optimize!(m)
    if termination_status(m) != MOI.INVALID_OPTION
        return PREFERRED
    else
        return "mumps"
    end
end
```
If I install Ipopt.jl without my own version of Ipopt (and hence without HSL):
```
Error loading HSL dynamic library libhsl.so: libhsl.so: não é possível abrir arquivo compartilhado: Arquivo ou diretório inexistente
This executable was not compiled with the HSL routine you specified.
You need to compile the HSL dynamic library to use deferred loading of the linear solver.
Abort...
```
And the Julia session is closed. Interesting enough if I search for ma57 instead of ma97 I get the expected behaviour, the system detects that is is not available and returns `mumps`. Only with m97 the system crashes.

I am using Ubuntu 20.04 and Julia 1.4.2.

**Comment by odow** [comment]
I'm not sure what we can do about this. Ipopt is calling `exit` instead of returning an error
https://github.com/coin-or/Ipopt/blob/641f2202f5594018ab0ebee6d1b7c6853ef83343/src/contrib/LinearSolverLoader/HSLLoader.c#L1255-L1256

**Comment by odow** [comment]
Closing since this is an upstream issue. You could open an issue at https://github.com/coin-or/Ipopt, but fixing it will likely require you to make a PR.
