### ISSUE TITLE
Export the change of the objective value and the unscaled constraint violation inf_pr during iteration to .csv file?

### ISSUE THREAD

**Issue by YuWVandy** [jump-dev/Ipopt.jl#216]
Hello everyone,
 Recently I've solved my nonlinear optimization problem and want to export the change of the obj value during the iteration to .csv file for the post-recession. I've searched online but haven't found any answer. Does anyone know how to do it? Or is there any other method to use for postprocessing?
 Thanks a lot！

**Comment by odow** [comment]
I"m not aware of functionality in Ipopt.jl to expose this information. It's probably easiest to copy-paste the log to a new file and parse it there.

**Comment by odow** [comment]
Closing because this doesn't appear to be implemented in the C API. It should probably be implemented via a callback.

**Comment by odow** [comment]
The `master` branch now exposes a callback which facilitates this. Here's an example: https://github.com/jump-dev/Ipopt.jl#solver-specific-callback
