### ISSUE TITLE
Using Ipopt.jl with SPRAL

### ISSUE THREAD

**Issue by ueliwechsler** [jump-dev/Ipopt.jl#223]
I'd like to connect `Ipopt.jl` with the linear solver backend [`SPRAL`](https://github.com/ralna/spral)

From what I read in the paper [Exploring Benefits of Linear Solver Parallelism on Modern Nonlinear Optimization Applications](https://arxiv.org/abs/1909.08104), it has already be done, but I couldn't figure out how to do it myself.

Is a SPRAL interface to the main C++ codebase of Ipopt needed or is there a more convenient way using `addOption(prob, "linear_solver", "custom")`?

**Comment by frapac** [comment]
For using Ipopt with SPRAL, I think you will need this particular fork of Ipopt: 
https://github.com/lanl-ansi/Ipopt
The installation instructions are detailed here: 
https://github.com/lanl-ansi/Ipopt/blob/master/COMPILE.md

According to the instructions, once Ipopt compiled, you will need to pass the following options to run Ipopt with SPRAL on the GPU: 
```
linear_solver spral
spral_use_gpu yes
```

**Comment by ueliwechsler** [comment]
Thank you for the links.

We haven't been able to compile it for Windows yet, but this is not an issue of `Ipopt.jl`.
If we manage to do it, I will post an update here for anybody that is interested.

**Comment by 0xDBFB7** [comment]
Just for the future wanderer: as of this date, the LANL branch has been merged into the devel branch of ipopt.

**Comment by amontoison** [comment]
@ueliwechsler @0xDBFB7 
Ipopt is now compiled with SPRAL if you are using Julia 1.9.
We added a section about it in the README.md: https://github.com/jump-dev/Ipopt.jl#spral
