### ISSUE TITLE
Ipopt Install Error: "ASL_jll" not found

### ISSUE THREAD

**Issue by Obtuya7** [jump-dev/Ipopt.jl#226]
Attempting to install Ipopt triggers the following error.

```julia
(prac.9.2020) pkg> add Ipopt
  Resolving package versions...
ERROR: KeyError: key "ASL_jll" not found
```
I have a fresh install of Julia 1.5.2 and I've tried VS Code and the REPL. I've only had this issue with Ipopt.jl.

The add request leaves a pkg entry without a version after failure. I've tried to remove and re-add but that doesn't solve the issue.

![image](https://user-images.githubusercontent.com/59591159/97762536-3c804300-1adf-11eb-8826-e6e01d25be47.png)

**Comment by dpo** [comment]
What platform?

**Comment by Obtuya7** [comment]
Windows 10

**Comment by dpo** [comment]
What happens if you just do `]add ASL_jll` in a fresh environment?

**Comment by Obtuya7** [comment]
```julia
pkg> add ASL_jll
  Resolving package versions...
ERROR: Unsatisfiable requirements detected for package ASL_jll [ae81ac8f]:
 ASL_jll [ae81ac8f] log:
 ├─ASL_jll [ae81ac8f] has no known versions!
 └─restricted to versions * by an explicit requirement — no versions left
```

**Comment by odow** [comment]
Your registry doesn't contain `ASL_jll`, which is weird. Run 
```
] rm Ipopt
] update
] add Ipopt
```

**Comment by odow** [comment]
Closing because this doesn't seem like an issue with Ipopt.jl.

If the above instructions didn't work and you are still having problems, post on the Community Forum: https://discourse.julialang.org/c/domain/opt/13, and include the full text output of:
```Julia
versioninfo()

import Pkg
Pkg.status()
Pkg.update()
Pkg.add("Ipopt")
Pkg.build("Ipopt")
```
People maintaining the package infrastructure may have more ideas of the problem.
