### ISSUE TITLE
How to retrieve time taken by solver

### ISSUE THREAD

**Issue by ferrolho** [jump-dev/Ipopt.jl#227]
Is there a way to retrieve the total time taken by the solver? I cannot find it in the [docs](https://coin-or.github.io/Ipopt/index.html). I am looking for the low-level C interface for this, not the MathOptInterface. Thank you! :slightly_smiling_face:

**Comment by ferrolho** [comment]
Thank you for looking into this. How can I do this without MathOptInterface? I cannot seem to find the right method in the C interface. If MathOptInterface gets it, it must exist somewhere... I tried looking for what MathOptInterface but I couldn't find it in https://github.com/jump-dev/Ipopt.jl/search?q=solve_time nor https://github.com/jump-dev/MathOptInterface.jl/search?q=solve_time.

**Comment by mlubin** [comment]
> If MathOptInterface gets it, it must exist somewhere...

MathOptInterface uses a timer: https://github.com/jump-dev/Ipopt.jl/blob/d9e9176620a9b527a08991a3d41062fa948867f7/src/MOI_wrapper.jl#L1391

**Comment by odow** [comment]
>  I cannot seem to find the right method in the C interface

There is no support for querying the solve time through the C interface:
https://github.com/coin-or/Ipopt/blob/master/src/Interfaces/IpStdCInterface.h

**Comment by ferrolho** [comment]
Thank you both. I was getting confused... Especially because https://github.com/jump-dev/Ipopt.jl/search?q=solve_time did not highlight that line @mlubin referenced!
![Screenshot from 2020-11-11 22-48-37](https://user-images.githubusercontent.com/4166093/98873392-33dd2480-2470-11eb-8878-0e0fdec2f3e7.png)

**Comment by odow** [comment]
Yes, the Github code-search feature leaves a lot to be desired.
