### ISSUE TITLE
"Instance Error 2 in DMUMPS_F77" with @threads

### ISSUE THREAD

**Issue by Brunobt80** [jump-dev/Ipopt.jl#245]
I'm trying to solve multiple problems in parallel using `@threads` macro, but I get the following error: `Instance Error 2 in DMUMPS_F77` on my Windows pc and `Aborted (core dumped)` on a Linux server. 

```
# example: optim.jl

using JuMP
using Ipopt

function optim()
    my_f(x,y) =  (1 - x) ^ 2 + 100 * (y - x ^ 2) ^ 2
    model = Model(with_optimizer(Ipopt.Optimizer,print_level=0))
    register(model, :my_f, 2, my_f, autodiff=true)
    @variable(model, x)
    @variable(model, y)
    @constraint(model, x + y == 10)
    @NLobjective(model, Min, my_f(x,y))
    optimize!(model)
    return value.([x,y])
end

function montecarlo()
    Threads.@threads for i ∈ 1:2
        optim()
    end
    println("***success***")
    return nothing
end

montecarlo()

# > julia optim.jl --threads 2

#   Instance Error 2 in DMUMPS_F77           1
# ** MPI_ABORT called
```

When single-threaded everything just works fine.

**Comment by odow** [comment]
JuMP uses a global variable for user-defined functions. It wouldn't surprise me if this isn't thread safe.

**Comment by odow** [comment]
Although the MUMPS error might be related to #242

**Comment by odow** [comment]
Closing because there doesn't seem anything to do at the Ipopt.jl level. MUMPS isn't thread safe.
