### ISSUE TITLE
better interaction with local installs

### ISSUE THREAD

**Issue by mlubin** [jump-dev/Ipopt.jl#25]
Currently, I believe that running Pkg.build() will overwrite `deps/deps.jl` if the user has pointed it to a local install. We should have a better way to handle this.
CC @tkelman

**Comment by tkelman** [comment]
I think the right way to do this is have the user add the path to their private install to `DL_LOAD_PATH`, then bindeps should hopefully pick up the library_dependency from that location.

**Comment by adowling2** [comment]
It would be great if the local install was detected and then bypassed downloading/compiling a separate version of Ipopt. I always compile my own (need HSL routines) and find it a waste to have a second copy.

**Comment by odow** [comment]
Closing because there is a way to do custom installations. Vagaries around HSL etc can be addressed by other issues.
