### ISSUE TITLE
Accessing Ipopt solver stats

### ISSUE THREAD

**Issue by sylvaticus** [jump-dev/Ipopt.jl#255]
As from comments [in the issue with the same title](https://github.com/jump-dev/JuMP.jl/issues/609) on  JuMP.jl, I am opening an issue here on Ipopt.jl to ask if does an API exist to query post-resolution solver statistics, like number of iterations and times (with and without function evaluations) ?

EDIT:

For reference, the C++ API for number of iterations is:

```C++
SmartPtr<IpoptApplication> application = new IpoptApplication();
// ...solve...
Index iter_count = application->Statistics()->IterationCount();
int icount = iter_count;
```

**Comment by odow** [comment]
I'm not aware of those functions in the C API. However, you can use a callback to access the logs: https://github.com/jump-dev/Ipopt.jl#solver-specific-callback
