### ISSUE TITLE
Deprecate and remove __init__

### ISSUE THREAD

**Issue by odow** [jump-dev/Ipopt.jl#261]
This should be removed at some point.

https://github.com/jump-dev/Ipopt.jl/blob/31a7ac15675f73ff68ea02f07a0b9eebdd8f6aac/src/Ipopt.jl#L64-L91

AmplNLWriter doesn't need it: https://github.com/jump-dev/AmplNLWriter.jl/issues/77

**Comment by KristofferC** [comment]
The part that sets the `LD_LIBRARY_PART` should especially much be removed since it can corrupt other parts of the system (e.g. https://discourse.julialang.org/t/link-checking-with-github-actions-not-working/61823/6).
