### ISSUE TITLE
IPOPT-HSL installation error!

### ISSUE THREAD

**Issue by muhammad9631** [jump-dev/Ipopt.jl#262]
Hello all, 

I was following step-by-step instruction mentioned in post #229 for the installation of custom binaries (like ASL, HSL) to be used in IPOPT. I got the HSL libraries from HSL and I was configuring them until I got this error 

```
checking for pkgconf... no
checking for pkg-config... no
checking for MC19... yes
checking for MA27... yes
checking for MA28... yes
checking for MA57... yes
checking for MA77... yes
checking for MA86... yes
checking for MA97... yes
checking for MC19S... no
checking for MA27S... no
checking for MA57S... no
checking for C interface to MC68... yes
checking for deps.f... yes
checking for deps90.f90... yes
checking for LAPACK... configure: error: "Cannot check for existence of module lapack without pkgconf"
```

It seems like there is no pkgconf. I have tried installing it using the instruction from this forum https://stackoverflow.com/questions/1710922/how-to-install-pkg-config-in-windows 

But still I am unable to successfully configure the HSL libraries. Has anyone received this error before OR can someone guide me how to overcome this issue?

I am using MSYS2 for doing the configuration and installation of HSL as well as IPOPT.

Thanks a lot in advance!

**Comment by odow** [comment]
I don't have any experience installing HSL with Ipopt on Windows. Ideally, you should only have to build HSL, and then use the dynamic linker with the Julia-provided Ipopt binary.

x-ref: https://github.com/jump-dev/Ipopt.jl/issues/247

**Comment by svigerske** [comment]
https://coin-or.github.io/Ipopt/INSTALL.html#SYSTEMPACKAGES_MSYS says that `pacman -S pkg-config` should give you pkg-config.

**Comment by odow** [comment]
Closing this as stale, and because it isn't related to Ipopt.jl. If you can confirm installation instructions for Windows, please post them in #247 (or open a PR) so we can update the documentation.
