### ISSUE TITLE
Ipopt uncostrainted with limited-memory Hessian crash

### ISSUE THREAD

**Issue by maksymkhomenko** [jump-dev/Ipopt.jl#264]
This is similar to previous issues on Julia #80 so I use that example. 

```julia
using Ipopt

const A = randn(10)
prob = createProblem(1, [-10.], [10.], 0, Float64[], Float64[], 0, 1,
           (x) -> sum(exp(x[1] .* A)),
           (x, g) -> println("shouldn't be called"),
           (x, grad_f) -> grad_f[1] = sum(exp(x[1] .* A) .* A),
           (x, mode, rows, cols, values) -> println("don't call me"),
           (x, mode, rows, cols, obj_factor, lambda, values) -> begin
               rows[1] = 1;
               cols[1] = 1;
               values[1]=sum(exp(x[1] .* A) .* A .* A)
           end)

status = solveProblem(prob)
```

The crash is solved by:

```Julia
(x, mode, rows, cols, obj_factor, lambda, values) -> begin
        if mode == :Structure
            rows[1] = 1;
            cols[1] = 1;
        else
            values[1] = sum(exp.(x[1] .* A) .* A .* A)
        end
    end,
```

However, if I use limited memory approximation option for hessian `addOption(model, "hessian_approximation", "limited-memory")`, it still causes a Julia crash. How one goes around this problem if it is not a bug?

**Comment by odow** [comment]
> it still causes a Julia crash

Please provide a stacktrace of the error.

**Comment by maksymkhomenko** [comment]
I hope this is what you mean. Thanks!

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x69043dc9 -- jl_gc_pool_alloc at /cygdrive/c/buildbot/worker/package_win64/build/src\gc.c:1148 [inlined]
jl_gc_alloc_ at /cygdrive/c/buildbot/worker/package_win64/build/src\julia_internal.h:277 [inlined]
jl_gc_alloc at /cygdrive/c/buildbot/worker/package_win64/build/src\gc.c:3150
in expression starting at none:0
jl_gc_pool_alloc at /cygdrive/c/buildbot/worker/package_win64/build/src\gc.c:1148 [inlined]
jl_gc_alloc_ at /cygdrive/c/buildbot/worker/package_win64/build/src\julia_internal.h:277 [inlined]
jl_gc_alloc at /cygdrive/c/buildbot/worker/package_win64/build/src\gc.c:3150
_new_array_ at /cygdrive/c/buildbot/worker/package_win64/build/src\array.c:94 [inlined]
_new_array at /cygdrive/c/buildbot/worker/package_win64/build/src\array.c:162 [inlined]
jl_alloc_array_1d at /cygdrive/c/buildbot/worker/package_win64/build/src\array.c:433
Array at .\boot.jl:406 [inlined]
Array at .\boot.jl:415 [inlined]
similar at .\abstractarray.jl:675 [inlined]
similar at .\abstractarray.jl:674 [inlined]
_array_for at .\array.jl:678 [inlined]
compute_live_ins at .\compiler/ssair\slot2ssa.jl:515
construct_ssa! at .\compiler/ssair\slot2ssa.jl:626
slot2reg at .\compiler/ssair\driver.jl:127 [inlined]
run_passes at .\compiler/ssair\driver.jl:134
optimize at .\compiler\optimize.jl:174
typeinf at .\compiler\typeinfer.jl:33
abstract_call_method_with_const_args at .\compiler\abstractinterpretation.jl:266
abstract_call_gf_by_type at .\compiler\abstractinterpretation.jl:134
abstract_call_known at .\compiler\abstractinterpretation.jl:904
abstract_call at .\compiler\abstractinterpretation.jl:926
abstract_call at .\compiler\abstractinterpretation.jl:911
abstract_eval at .\compiler\abstractinterpretation.jl:1005
typeinf_local at .\compiler\abstractinterpretation.jl:1270
typeinf_nocycle at .\compiler\abstractinterpretation.jl:1326
typeinf at .\compiler\typeinfer.jl:12
typeinf_edge at .\compiler\typeinfer.jl:484
abstract_call_method at .\compiler\abstractinterpretation.jl:419
abstract_call_gf_by_type at .\compiler\abstractinterpretation.jl:111
abstract_call_known at .\compiler\abstractinterpretation.jl:904
abstract_call at .\compiler\abstractinterpretation.jl:926
abstract_call at .\compiler\abstractinterpretation.jl:911
abstract_eval at .\compiler\abstractinterpretation.jl:1005
typeinf_local at .\compiler\abstractinterpretation.jl:1270
typeinf_nocycle at .\compiler\abstractinterpretation.jl:1326
typeinf at .\compiler\typeinfer.jl:12
typeinf_edge at .\compiler\typeinfer.jl:484
abstract_call_method at .\compiler\abstractinterpretation.jl:419
abstract_call_gf_by_type at .\compiler\abstractinterpretation.jl:111
abstract_call_known at .\compiler\abstractinterpretation.jl:904
abstract_call at .\compiler\abstractinterpretation.jl:926
abstract_call at .\compiler\abstractinterpretation.jl:911
abstract_eval at .\compiler\abstractinterpretation.jl:1005
typeinf_local at .\compiler\abstractinterpretation.jl:1270
typeinf_nocycle at .\compiler\abstractinterpretation.jl:1326
typeinf at .\compiler\typeinfer.jl:12
typeinf_edge at .\compiler\typeinfer.jl:484
abstract_call_method at .\compiler\abstractinterpretation.jl:419
abstract_call_gf_by_type at .\compiler\abstractinterpretation.jl:111
abstract_call_known at .\compiler\abstractinterpretation.jl:904
abstract_call at .\compiler\abstractinterpretation.jl:926
abstract_call at .\compiler\abstractinterpretation.jl:911
abstract_eval at .\compiler\abstractinterpretation.jl:1005
typeinf_local at .\compiler\abstractinterpretation.jl:1270
typeinf_nocycle at .\compiler\abstractinterpretation.jl:1326
typeinf at .\compiler\typeinfer.jl:12
typeinf_edge at .\compiler\typeinfer.jl:484
abstract_call_method at .\compiler\abstractinterpretation.jl:419
abstract_call_gf_by_type at .\compiler\abstractinterpretation.jl:111
abstract_call_known at .\compiler\abstractinterpretation.jl:904
abstract_call at .\compiler\abstractinterpretation.jl:926
abstract_call at .\compiler\abstractinterpretation.jl:911
abstract_eval at .\compiler\abstractinterpretation.jl:1005
typeinf_local at .\compiler\abstractinterpretation.jl:1270
typeinf_nocycle at .\compiler\abstractinterpretation.jl:1326
typeinf at .\compiler\typeinfer.jl:12
typeinf_ext at .\compiler\typeinfer.jl:570
typeinf_ext at .\compiler\typeinfer.jl:601
jfptr_typeinf_ext_20437.clone_1 at C:\Users\xkhomm\AppData\Local\Programs\Julia 1.5.3\lib\julia\sys.dll (unknown line)
_jl_invoke at /cygdrive/c/buildbot/worker/package_win64/build/src\gf.c:2214 [inlined]
jl_apply_generic at /cygdrive/c/buildbot/worker/package_win64/build/src\gf.c:2398 [inlined]
jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1690 [inlined]
jl_type_infer at /cygdrive/c/buildbot/worker/package_win64/build/src\gf.c:296
jl_generate_fptr at /cygdrive/c/buildbot/worker/package_win64/build/src\jitlayers.cpp:290
jl_compile_method_internal at /cygdrive/c/buildbot/worker/package_win64/build/src\gf.c:1964
jl_compile_method_internal at /cygdrive/c/buildbot/worker/package_win64/build/src\gf.c:1931 [inlined]
_jl_invoke at /cygdrive/c/buildbot/worker/package_win64/build/src\gf.c:2224 [inlined]
jl_apply_generic at /cygdrive/c/buildbot/worker/package_win64/build/src\gf.c:2398
#208 at C:\Users\xkhomm\.julia\packages\Atom\isnka\src\eval.jl:136
unknown function (ip: 000000001b919213)
jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1690 [inlined]
do_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\builtins.c:655
jl_f__apply at /cygdrive/c/buildbot/worker/package_win64/build/src\builtins.c:669 [inlined]
jl_f__apply_latest at /cygdrive/c/buildbot/worker/package_win64/build/src\builtins.c:705
#invokelatest#1 at .\essentials.jl:710 [inlined]
invokelatest at .\essentials.jl:709 [inlined]
macro expansion at C:\Users\xkhomm\.julia\packages\Media\ItEPc\src\dynamic.jl:24 [inlined]
eval at C:\Users\xkhomm\.julia\packages\Atom\isnka\src\eval.jl:113
unknown function (ip: 00000000306568a3)
jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1690 [inlined]
do_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\builtins.c:655
jl_f__apply at /cygdrive/c/buildbot/worker/package_win64/build/src\builtins.c:669 [inlined]
jl_f__apply_latest at /cygdrive/c/buildbot/worker/package_win64/build/src\builtins.c:705
#invokelatest#1 at .\essentials.jl:710
jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1690 [inlined]
do_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\builtins.c:655
invokelatest at .\essentials.jl:709
jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1690 [inlined]
do_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\builtins.c:655
macro expansion at C:\Users\xkhomm\.julia\packages\Atom\isnka\src\eval.jl:41 [inlined]
#188 at .\task.jl:356
unknown function (ip: 000000001b83a793)
jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1690 [inlined]
start_task at /cygdrive/c/buildbot/worker/package_win64/build/src\task.c:705
Allocations: 111486193 (Pool: 111465198; Big: 20995); GC: 77

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x69043dc9 -- jl_gc_pool_alloc at /cygdrive/c/buildbot/worker/package_win64/build/src\gc.c:1148 [inlined]
jl_gc_alloc_ at /cygdrive/c/buildbot/worker/package_win64/build/src\julia_internal.h:277 [inlined]
jl_gc_alloc at /cygdrive/c/buildbot/worker/package_win64/build/src\gc.c:3150
in expression starting at none:0
jl_gc_pool_alloc at /cygdrive/c/buildbot/worker/package_win64/build/src\gc.c:1148 [inlined]
jl_gc_alloc_ at /cygdrive/c/buildbot/worker/package_win64/build/src\julia_internal.h:277 [inlined]
jl_gc_alloc at /cygdrive/c/buildbot/worker/package_win64/build/src\gc.c:3150
_new_array_ at /cygdrive/c/buildbot/worker/package_win64/build/src\array.c:94
jl_deserialize_value_array at /cygdrive/c/buildbot/worker/package_win64/build/src\dump.c:1607
jl_deserialize_value at /cygdrive/c/buildbot/worker/package_win64/build/src\dump.c:2136
jl_uncompress_ir at /cygdrive/c/buildbot/worker/package_win64/build/src\dump.c:2676
retrieve_code_info at .\compiler\utilities.jl:110 [inlined]
InferenceState at .\compiler\inferencestate.jl:118
typeinf_ext at .\compiler\typeinfer.jl:568
typeinf_ext at .\compiler\typeinfer.jl:601
jfptr_typeinf_ext_20437.clone_1 at C:\Users\xkhomm\AppData\Local\Programs\Julia 1.5.3\lib\julia\sys.dll (unknown line)
_jl_invoke at /cygdrive/c/buildbot/worker/package_win64/build/src\gf.c:2214 [inlined]
jl_apply_generic at /cygdrive/c/buildbot/worker/package_win64/build/src\gf.c:2398 [inlined]
jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1690 [inlined]
jl_type_infer at /cygdrive/c/buildbot/worker/package_win64/build/src\gf.c:296
jl_generate_fptr at /cygdrive/c/buildbot/worker/package_win64/build/src\jitlayers.cpp:290
jl_compile_method_internal at /cygdrive/c/buildbot/worker/package_win64/build/src\gf.c:1964
jl_compile_method_internal at /cygdrive/c/buildbot/worker/package_win64/build/src\gf.c:1931 [inlined]
_jl_invoke at /cygdrive/c/buildbot/worker/package_win64/build/src\gf.c:2224 [inlined]
jl_apply_generic at /cygdrive/c/buildbot/worker/package_win64/build/src\gf.c:2398
_atexit at .\initdefs.jl:316
jfptr__atexit_47558.clone_1 at C:\Users\xkhomm\AppData\Local\Programs\Julia 1.5.3\lib\julia\sys.dll (unknown line)
jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1690 [inlined]
jl_atexit_hook at /cygdrive/c/buildbot/worker/package_win64/build/src\init.c:230
jl_exit at /cygdrive/c/buildbot/worker/package_win64/build/src\jl_uv.c:624
jl_exception_handler at /cygdrive/c/buildbot/worker/package_win64/build/src\signals-win.c:317
__julia_personality at /cygdrive/c/buildbot/worker/package_win64/build/src/support\win32_ucontext.c:28
_chkstk at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
RtlWalkFrameChain at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
KiUserExceptionDispatcher at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
jl_gc_pool_alloc at /cygdrive/c/buildbot/worker/package_win64/build/src\gc.c:1147 [inlined]
jl_gc_alloc_ at /cygdrive/c/buildbot/worker/package_win64/build/src\julia_internal.h:277 [inlined]
jl_gc_alloc at /cygdrive/c/buildbot/worker/package_win64/build/src\gc.c:3150
_new_array_ at /cygdrive/c/buildbot/worker/package_win64/build/src\array.c:94 [inlined]
_new_array at /cygdrive/c/buildbot/worker/package_win64/build/src\array.c:162 [inlined]
jl_alloc_array_1d at /cygdrive/c/buildbot/worker/package_win64/build/src\array.c:433
Array at .\boot.jl:406 [inlined]
Array at .\boot.jl:415 [inlined]
similar at .\abstractarray.jl:675 [inlined]
similar at .\abstractarray.jl:674 [inlined]
_array_for at .\array.jl:678 [inlined]
compute_live_ins at .\compiler/ssair\slot2ssa.jl:515
construct_ssa! at .\compiler/ssair\slot2ssa.jl:626
slot2reg at .\compiler/ssair\driver.jl:127 [inlined]
run_passes at .\compiler/ssair\driver.jl:134
optimize at .\compiler\optimize.jl:174
typeinf at .\compiler\typeinfer.jl:33
abstract_call_method_with_const_args at .\compiler\abstractinterpretation.jl:266
abstract_call_gf_by_type at .\compiler\abstractinterpretation.jl:134
abstract_call_known at .\compiler\abstractinterpretation.jl:904
abstract_call at .\compiler\abstractinterpretation.jl:926
abstract_call at .\compiler\abstractinterpretation.jl:911
abstract_eval at .\compiler\abstractinterpretation.jl:1005
typeinf_local at .\compiler\abstractinterpretation.jl:1270
typeinf_nocycle at .\compiler\abstractinterpretation.jl:1326
typeinf at .\compiler\typeinfer.jl:12
typeinf_edge at .\compiler\typeinfer.jl:484
abstract_call_method at .\compiler\abstractinterpretation.jl:419
abstract_call_gf_by_type at .\compiler\abstractinterpretation.jl:111
abstract_call_known at .\compiler\abstractinterpretation.jl:904
abstract_call at .\compiler\abstractinterpretation.jl:926
abstract_call at .\compiler\abstractinterpretation.jl:911
abstract_eval at .\compiler\abstractinterpretation.jl:1005
typeinf_local at .\compiler\abstractinterpretation.jl:1270
typeinf_nocycle at .\compiler\abstractinterpretation.jl:1326
typeinf at .\compiler\typeinfer.jl:12
typeinf_edge at .\compiler\typeinfer.jl:484
abstract_call_method at .\compiler\abstractinterpretation.jl:419
abstract_call_gf_by_type at .\compiler\abstractinterpretation.jl:111
abstract_call_known at .\compiler\abstractinterpretation.jl:904
abstract_call at .\compiler\abstractinterpretation.jl:926
abstract_call at .\compiler\abstractinterpretation.jl:911
abstract_eval at .\compiler\abstractinterpretation.jl:1005
typeinf_local at .\compiler\abstractinterpretation.jl:1270
typeinf_nocycle at .\compiler\abstractinterpretation.jl:1326
typeinf at .\compiler\typeinfer.jl:12
typeinf_edge at .\compiler\typeinfer.jl:484
abstract_call_method at .\compiler\abstractinterpretation.jl:419
abstract_call_gf_by_type at .\compiler\abstractinterpretation.jl:111
abstract_call_known at .\compiler\abstractinterpretation.jl:904
abstract_call at .\compiler\abstractinterpretation.jl:926
abstract_call at .\compiler\abstractinterpretation.jl:911
abstract_eval at .\compiler\abstractinterpretation.jl:1005
typeinf_local at .\compiler\abstractinterpretation.jl:1270
typeinf_nocycle at .\compiler\abstractinterpretation.jl:1326
typeinf at .\compiler\typeinfer.jl:12
typeinf_edge at .\compiler\typeinfer.jl:484
abstract_call_method at .\compiler\abstractinterpretation.jl:419
abstract_call_gf_by_type at .\compiler\abstractinterpretation.jl:111
abstract_call_known at .\compiler\abstractinterpretation.jl:904
abstract_call at .\compiler\abstractinterpretation.jl:926
abstract_call at .\compiler\abstractinterpretation.jl:911
abstract_eval at .\compiler\abstractinterpretation.jl:1005
typeinf_local at .\compiler\abstractinterpretation.jl:1270
typeinf_nocycle at .\compiler\abstractinterpretation.jl:1326
typeinf at .\compiler\typeinfer.jl:12
typeinf_ext at .\compiler\typeinfer.jl:570
typeinf_ext at .\compiler\typeinfer.jl:601
jfptr_typeinf_ext_20437.clone_1 at C:\Users\xkhomm\AppData\Local\Programs\Julia 1.5.3\lib\julia\sys.dll (unknown line)
_jl_invoke at /cygdrive/c/buildbot/worker/package_win64/build/src\gf.c:2214 [inlined]
jl_apply_generic at /cygdrive/c/buildbot/worker/package_win64/build/src\gf.c:2398 [inlined]
jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1690 [inlined]
jl_type_infer at /cygdrive/c/buildbot/worker/package_win64/build/src\gf.c:296
jl_generate_fptr at /cygdrive/c/buildbot/worker/package_win64/build/src\jitlayers.cpp:290
jl_compile_method_internal at /cygdrive/c/buildbot/worker/package_win64/build/src\gf.c:1964
jl_compile_method_internal at /cygdrive/c/buildbot/worker/package_win64/build/src\gf.c:1931 [inlined]
_jl_invoke at /cygdrive/c/buildbot/worker/package_win64/build/src\gf.c:2224 [inlined]
jl_apply_generic at /cygdrive/c/buildbot/worker/package_win64/build/src\gf.c:2398
#208 at C:\Users\xkhomm\.julia\packages\Atom\isnka\src\eval.jl:136
unknown function (ip: 000000001b919213)
jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1690 [inlined]
do_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\builtins.c:655
jl_f__apply at /cygdrive/c/buildbot/worker/package_win64/build/src\builtins.c:669 [inlined]
jl_f__apply_latest at /cygdrive/c/buildbot/worker/package_win64/build/src\builtins.c:705
#invokelatest#1 at .\essentials.jl:710 [inlined]
invokelatest at .\essentials.jl:709 [inlined]
macro expansion at C:\Users\xkhomm\.julia\packages\Media\ItEPc\src\dynamic.jl:24 [inlined]
eval at C:\Users\xkhomm\.julia\packages\Atom\isnka\src\eval.jl:113
unknown function (ip: 00000000306568a3)
jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1690 [inlined]
do_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\builtins.c:655
jl_f__apply at /cygdrive/c/buildbot/worker/package_win64/build/src\builtins.c:669 [inlined]
jl_f__apply_latest at /cygdrive/c/buildbot/worker/package_win64/build/src\builtins.c:705
#invokelatest#1 at .\essentials.jl:710
jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1690 [inlined]
do_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\builtins.c:655
invokelatest at .\essentials.jl:709
jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1690 [inlined]
do_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\builtins.c:655
macro expansion at C:\Users\xkhomm\.julia\packages\Atom\isnka\src\eval.jl:41 [inlined]
#188 at .\task.jl:356
unknown function (ip: 000000001b83a793)
jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1690 [inlined]
start_task at /cygdrive/c/buildbot/worker/package_win64/build/src\task.c:705
Allocations: 111486193 (Pool: 111465198; Big: 20995); GC: 77

**Comment by maksymkhomenko** [comment]
After posting this, I realize that this presumably happens because the vector of initial parameters did not correspond to the provided number of variables. Then the crash disappears. At the end it is my fault.
