### ISSUE TITLE
Compiling mpi with pardiso on ubuntu 

### ISSUE THREAD

**Issue by JOHN194872** [jump-dev/Ipopt.jl#266]
I am trying to compile laplace_mpi.c but get:
laplace_mpi.c:(.text+0x1250): undefined reference to `pardiso_mpi_init_c_' etc
Please help.
Thanks,
John

**Comment by odow** [comment]
You're likely missing some compilation flags. (Did you mean to post this here? I don't see what this has to do with Ipopt.jl.)

Note that you don't need to compile Ipopt to use different linear solvers: https://github.com/jump-dev/Ipopt.jl#linear-solvers

**Comment by JOHN194872** [comment]
Hi Odow,
Thanks for your reply.
I am using the following to compile:
mpicc -o laplace laplace_mpi.c -L. -lpardiso600-GNU720-X86-64 -llapack -lrefblas -lgfortran -fopenmp -lpthread -ldl -lstdc++ -lm
which works for gcc instead of mpicc.
Regards,
John

**Comment by JOHN194872** [comment]
Hi Odow,
I should have said:
I am using the following to try to compile:
mpicc -o laplace laplace_mpi.c -L. -lpardiso600-GNU720-X86-64 -llapack -lrefblas -lgfortran -fopenmp -lpthread -ldl -lstdc++ -lm
which works for gcc instead of mpicc.
Have you succeeded in compiling this yourself?
Thanks,
John

**Comment by odow** [comment]
> Have you succeeded in compiling this yourself?

No. I'm not sure what `laplace_mpi` is, or what this has to do with Ipopt.jl. Are you trying to use Ipopt through Julia?

**Comment by JOHN194872** [comment]
No, I am not trying to use lpopt.
Regards
John

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by odow** [comment]
Closing because this is not related to Ipopt.jl, but unfortunately, I'm not sure where you should go for more help.
