### ISSUE TITLE
Typo in README: Linear Solvers

### ISSUE THREAD

**Issue by loicvh** [jump-dev/Ipopt.jl#269]
The Linux explanation for the installation of Pardiso contains a minor typo at step 4:

> Alternatively, if the library is located at /full/path/libpardiso.dylib

`.dylib` is the extension for MacOS, it should read

> Alternatively, if the library is located at /full/path/libpardiso.so

Also, it could be nice to explain how to add to the load path, e.g.,

```
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/full/path/"
```
I can create a quick PR for this (really minor) issue.

**Comment by odow** [comment]
Closed by #270 

Thanks @loicvh
