### ISSUE TITLE
max_wall_time is not a valid option ?

### ISSUE THREAD

**Issue by adrien-le-franc** [jump-dev/Ipopt.jl#279]
Hi, 
I am trying to use the option "max_wall_time" as in https://coin-or.github.io/Ipopt/OPTIONS.html by setting e.g. 20 seconds of max wall time with ```addOption(prob, "max_wall_time", 20.)``` for the toy problem in the example folder, but I get an error:
````
Tried to set Option: max_wall_time. It is not a valid option. Please check the list of available options.
ERROR: LoadError: IPOPT: Couldn't set option 'max_wall_time' to value '20'.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] addOption(::IpoptProblem, ::String, ::String) at /opt/julia/packages/Ipopt/vtrOr/src/Ipopt.jl:404
 [3] top-level scope at /home/ZNI/NIZx.jl/x1/test.jl:113
 [4] include(::String) at ./client.jl:457
 [5] top-level scope at REPL[3]:1
in expression starting at /home/ZNI/NIZx.jl/x1/test.jl:113
````
I find it surprising since the documentation of this package doesn't warn against non implemented options, also other options like "max_cpu_time" work for me. Do you confirm that this option is not valid ?

**Comment by odow** [comment]
It's not supported yet: https://github.com/jump-dev/Ipopt.jl/pull/277

**Comment by odow** [comment]
Closing in favor of #278
