### ISSUE TITLE
Bump minimum requirement for Julia to stop depending on BinaryProvider

### ISSUE THREAD

**Issue by andreasnoack** [jump-dev/Ipopt.jl#293]
The dependence on BinaryProvider is causing issues, see https://github.com/PumasAI/PumasSystemImages.jl/issues/52, and a new long term support version of Julia has been announced, so it would be great if you could consider dropping the BinaryProvider dependency.

**Comment by andreasnoack** [comment]
I now realize that more recent versions, you only load BinaryProvider for old Julia versions.

**Comment by odow** [comment]
The Pumas link is private. 

Once 1.6 is the LTS,  I think we're going to have a conversation about how long we continue supporting 1.0 for. My preference is to continue support unless there is a strong reason otherwise.

**Comment by andreasnoack** [comment]
I think it's fine since you've been careful not to load BinaryProvider on more recent versions of Julia. The issue was that PackageCompiler by default loads all dependencies unconditionally and https://github.com/JuliaPackaging/BinaryProvider.jl/blob/55aeaea2652c1b43ba882c2f833196e99f10e2db/src/BinaryProvider.jl#L36 makes it impossible to relocate the binary. Ideally, that line should be changed but there is little incentive to do that now that everybody has moved on from BinaryProvider. We found a PackageCompiler flag that avoids the unconditional loading of all dependencies so we are good.

**Comment by jaakkor2** [comment]
> We found a PackageCompiler flag that avoids the unconditional loading of all dependencies so we are good.

The keyword option for `PackageCompiler.create_sysimage` seems to be `include_transitive_dependencies=false`.
