### ISSUE TITLE
MA86 compile or library failure on WSL/Ubuntu within Windows: undefined symbol: cgemv_

### ISSUE THREAD

**Issue by niclasmattsson** [jump-dev/Ipopt.jl#300]
I'm trying to use MA86 in IPOPT on my Windows system, so I've resorted to compiling it in WSL (Ubuntu). Following the README instructions sort of worked (see further below), but when solving a model using IPOPT in Julia I get this error:

```
Exception of type: DYNAMIC_LIBRARY_FAILURE in file "Common/IpLibraryLoader.cpp" at line 67:
 Exception message: /home/niclas/julia-1.7.1/bin/libhsl.so: undefined symbol: cgemv_

EXIT: Library loading failure.
```

Possibly related: during the compilation I had the following problem during `./configure`:

```
configure: WARNING: No BLAS library found. make check will not work.
checking for METIS library... checking for metis_nodend_ in -L -lmetis... no
checking for metis_nodend_ in -lmetis... no
./configure: line 20798: hsl_metis_ok: command not found
configure: WARNING: No MeTiS library found. make check will not work.
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating example/Fortran/Makefile
config.status: creating example/C/Makefile
config.status: executing depfiles commands
config.status: error: in `/home/niclas/hsl_ma86-1.6.0':
config.status: error: Something went wrong bootstrapping makefile fragments
    for automatic dependency tracking.  Try re-running configure with the
    '--disable-dependency-tracking' option to at least be able to build
    the package (albeit without support for automatic dependency tracking).
See `config.log' for more details
```

I couldn't tell if this was fatal or not so i just tried `./configure --disable-dependency-tracking` instead. That seemed to work, and I renamed the resulting `libhsl_ma86.so.0.0.0` to `libhsl.so` as per the instructions. And then got the error at the top when using it. Any ideas?

**Comment by odow** [comment]
Is this to compile MA86 by itself? What was the full list of commands you ran? 

It looks like you need a BLAS and LAPACK. Something like `sudo apt-get install libblas-dev liblapack-dev`? 

I don't have any experience compiling on WSL, so I won't be much help. This doesn't seem related to Ipopt (which should just work if you can get a libhls.so file). 

Here are other instructions: https://github-wiki-see.page/m/casadi/casadi/wiki/Obtaining-HSL

If you get something working, please make a pull request to update the instructions.

**Comment by CMGeldenhuys** [comment]
I ran into a similar error (different undefined symbol):
```
Exception of type: DYNAMIC_LIBRARY_FAILURE in file "Common/IpLibraryLoader.cpp" at line 67: 
Exception message: /usr/local/lib/libhsl.so: undefined symbol: dtrmm_
```
Managed to get it working by following the instruction listed in: https://github.com/coin-or-tools/ThirdParty-HSL#installation-steps

Not entirely sure if our problems are related.

**Comment by odow** [comment]
> Managed to get it working

Also on WSL? If you have suggestions for improved documentation, please consider making a pull request: https://github.com/jump-dev/Ipopt.jl/edit/master/README.md

**Comment by CMGeldenhuys** [comment]
> Also on WSL?

Sorry, no I had a similar error on Fedora 34 (Julia 1.7.2) and on the [Julia docker image](https://hub.docker.com/_/julia) (version 1.7.2) using HSL version 2021.05.05.

>If you have suggestions for improved documentation, please consider making a pull request

Will do, maybe @niclasmattsson can check if it works on WSL? I don't have access to a windows machine so I can't check if it works on WSL.


These are the steps I followed on Debian (Julia docker image):
```shell
# Build tools
apt install gcc gfortran pkgconf

# BLAS/LAPACK not sure if all these are needed?
apt install libopenblas-dev libblas-dev liblapack-dev libopenblas64-dev libblas64-dev liblapack64-dev

# Clone ThirdParty-HSL
git clone https://github.com/coin-or-tools/ThirdParty-HSL.git
cd ThirdParty-HSL

# Unpack coinhsl
gunzip coinhsl-x.y.z.tar.gz
tar xf coinhsl-x.y.z.tar
mv coinhsl-x.y.z coinhsl

# Build HSL
./configure --prefix=</full/path/somewhere>
make
make install
cd /full/path/somewhere/lib/
ln -s libcoinhsl.so libhsl.so
export LD_LIBRARY_PATH=/full/path/somewhere/lib; julia
```
```julia
...

julia> set_optimizer_attribute(model, "linear_solver", "ma97")

julia> optimize!(model)

******************************************************************************
This program contains Ipopt, a library for large-scale nonlinear optimization.
 Ipopt is released as open source code under the Eclipse Public License (EPL).
         For more information visit https://github.com/coin-or/Ipopt
******************************************************************************

This is Ipopt version 3.14.4, running with linear solver ma97.
```

**Comment by niclasmattsson** [comment]
Thanks everyone for the suggestions! I can now confirm that MA86 is working for me under WSL (under Windows 10). I strongly recommend installing it, even if there is a performance penalty when you run it under WSL. For example, in my tests of large nonlinear energy models, IPOPT with MUMPS solves about 50% slower under WSL than in native Windows. But MA86 is so much faster that the net solve time under WSL is about 40% faster than the MUMPS Windows time, and solves more reliably as well. I'm still on WSL 1 so maybe it becomes even faster when I upgrade to WSL 2.

Here's my compilation sequence to get the HSL library installed into ~/lib:

```
mkdir ~/lib
nano .profile   # then add the following line
        export LD_LIBRARY_PATH=$HOME/lib
sudo apt-get update
sudo apt install gfortran
sudo apt-get install libblas-dev libmetis-dev
sudo apt install make
# download hsl_ma86-1.6.0.tar.gz from HSL website (URL received after licensing completed)
tar zxvf hsl_ma86-1.6.0.tar.gz
cd hsl_ma86-1.6.0/
./configure --prefix=/home/YOUR_USER_NAME
make
sudo make install
cd ~/lib
sudo ln -s libhsl_ma86.so.0.0.0 libhsl.so
```

On a side note: I got another huge improvement in solve times and reliability by changing IPOPT's barrier setting strategy, like this:

```
set_optimizer_attributes(model, "linear_solver" => "ma86",  "max_iter" => 100000, "mu_strategy" => "adaptive")
```
