### ISSUE TITLE
initiating the lagrangian multiplier (init_lambda)

### ISSUE THREAD

**Issue by AhmedAlreweny** [jump-dev/Ipopt.jl#310]
Hi, 
I wonder if there is a way to set the lambda to values other than zeros. As far as I can see [here](https://coin-or.github.io/Ipopt/classIpopt_1_1TNLP.html#a0ae4075da9928e518780bba865698545), this can be done in the original C++ interface. Is it also possible in the C wrapper?

**Comment by blegat** [comment]
Yes, see https://jump.dev/JuMP.jl/stable/reference/nlp/#JuMP.set_nonlinear_dual_start_value

**Comment by odow** [comment]
Closing because this isn't a bug in Ipopt. If you can't get it to work, please post on the community forum, https://discourse.julialang.org/c/domain/opt/13, and we can discuss further.
