### ISSUE TITLE
copy_to does not copy attributes for variable bound constraints

### ISSUE THREAD

**Issue by LukasBarner** [jump-dev/Ipopt.jl#333]
When calling copy_to, at some point MOI.pass_attributes gets called (via MOI.Utilities.default_copy_to()):
```julia
function MOI.copy_to(model::Optimizer, src::MOI.ModelLike)
    return MOI.Utilities.default_copy_to(model, src)
end
```
```julia
function pass_attributes(
    dest::MOI.ModelLike,
    src::MOI.ModelLike,
    index_map::IndexMap,
    cis_src::Vector{MOI.ConstraintIndex{F,S}},
) where {F,S}
    for attr in MOI.get(src, MOI.ListOfConstraintAttributesSet{F,S}())
        if !MOI.supports(dest, attr, MOI.ConstraintIndex{F,S})
            if (
                attr == MOI.ConstraintName() ||
                attr == MOI.ConstraintPrimalStart() ||
                attr == MOI.ConstraintDualStart()
            )
                continue  # Skipping names and start values is okay.
            end
        end
        _pass_attribute(dest, src, index_map, cis_src, attr)
    end
    return
end
```
currently, MOI.supports() in this case is defined as follows: 
```julia
function MOI.supports(
    ::Optimizer,
    ::MOI.ConstraintDualStart,
    ::Type{MOI.ConstraintIndex{F,S}},
) where {F<:_FUNCTIONS,S<:_SETS}
    return true
end
```
where 
```julia
const _SETS =
    Union{MOI.GreaterThan{Float64},MOI.LessThan{Float64},MOI.EqualTo{Float64}}

const _FUNCTIONS = Union{
    MOI.ScalarAffineFunction{Float64},
    MOI.ScalarQuadraticFunction{Float64},
}
```
This results in the fact that attributes for variable bound constraints are not copied, since calling MOI.supports() for bound constraints (where F=MOI.VariableIndex) returns the default false and attributes are not passed using
```julia
 _pass_attribute(dest, src, index_map, cis_src, attr)
```
Extending the MOI.supports definition to variable bounds creates a lot of other problems. 
However, things such as ConstraintDualStart have get/set methods that work as desired. 
Would it be a good idea to include these attributes manually in the copy_to function? I was thinking of something like this: 
```julia
function MOI.copy_to(model::Optimizer, src::MOI.ModelLike)
    idxmap =  MOI.Utilities.default_copy_to(model, src)
    # copy relevant attributes here
    return idxmap
end
```
If so, I would be happy to start with a PR at least implementing the dual start values. 
In case this is not a good idea, a brief warning about not copying bound dual starting values would maybe be good. 
This also relates to the other attributes skipped by the continue statement in pass_attributes(), but I think bound dual starting values are the most relevant (primal starts are defined by variable primal starts, and copying names for bounds is also not really relevant...).

**Comment by odow** [comment]
`ConstraintDualStart` for `VariableIndex` are handled here:
https://github.com/jump-dev/Ipopt.jl/blob/4ae7ae970a94932534b7fca169e614fbd85527c3/src/MOI_wrapper.jl#L339-L425

Do you have an example where you can show they aren't being copied?

**Comment by LukasBarner** [comment]
In general, setting dual starts works. It is just that the information is lost during copy_to, since MOI.supports() from Ipopt.jl returns the default false if a constraint of type VariableIndex-in-S is passed. 
Here is a very ugly example, but it shows the problem

```julia
using MathOptInterface,Ipopt
MOIU = MathOptInterface.Utilities 
MOI = MathOptInterface

model = MOIU.CachingOptimizer(MOIU.UniversalFallback(MOIU.Model{Float64}()), MOIU.AUTOMATIC)
varidx = MOI.add_variable(model)
MOI.set(model, MOI.ObjectiveFunction{MOI.VariableIndex}(),varidx)
MOI.set(model, MOI.ObjectiveSense(),MOI.MIN_SENSE)
ctridx = MOI.add_constraint(model, varidx, MOI.GreaterThan(0.0))

MOI.set(model, MOI.ConstraintDualStart(), ctridx, 2.0)
@assert MOI.get(model, MOI.ConstraintDualStart(), ctridx)==2

solver = MOI.instantiate(Ipopt.Optimizer)
idxmap = MOI.copy_to(solver,model)

@assert MOI.get(solver, MOI.ConstraintDualStart(), idxmap[ctridx])==nothing
# That duals to bounds are not correctly set is visible from the log
MOI.set(solver, MOI.RawOptimizerAttribute("warm_start_init_point"), "yes")
MOI.set(solver, MOI.RawOptimizerAttribute("print_level"), 8)
MOI.optimize!(solver)

# But setting the constraint dual start in general works:
MOI.set(solver, MOI.ConstraintDualStart(), idxmap[ctridx], 2)
@assert MOI.get(solver, MOI.ConstraintDualStart(), idxmap[ctridx]) == 2
MOI.optimize!(solver)
```
The only attributes that can get ignored during copy without an error/warning are MOI.ConstraintName(), MOI.ConstraintPrimalStart() and MOI.ConstraintDualStart() (as defined by pass_attributes) .
Setting these in the Ipopt.copy_to() function after the default_copy_to() call might be an easy workaround.

**Comment by odow** [comment]
Ooops. We need `::Type{<:MOI.ConstraintIndex{MOI.VariableIndex,<:_SETS}}`. I'll make a PR.

**Comment by odow** [comment]
This should fix it: https://github.com/jump-dev/Ipopt.jl/pull/334

**Comment by LukasBarner** [comment]
Thanks for the quick action. I tried that as well, but (on my end), it resulted in different problems. Please see the following slightly edited example from above: 
```julia
using MathOptInterface, Ipopt
MOIU = MathOptInterface.Utilities 
MOI = MathOptInterface

model = MOIU.CachingOptimizer(MOIU.UniversalFallback(MOIU.Model{Float64}()), MOIU.AUTOMATIC)
varidx = MOI.add_variable(model)
MOI.set(model, MOI.ObjectiveFunction{MOI.VariableIndex}(),varidx)
MOI.set(model, MOI.ObjectiveSense(),MOI.MIN_SENSE)
ctridx = MOI.add_constraint(model, varidx, MOI.GreaterThan(0.0))

MOI.set(model, MOI.ConstraintDualStart(), ctridx, 2.0)
@assert MOI.get(model, MOI.ConstraintDualStart(), ctridx)==2

solver = MathOptInterface.instantiate(Ipopt.Optimizer; with_bridge_type=Float64)
idxmap = MOI.copy_to(solver,model)
```
This was working fine prior to fixing the type issue, but threw an error after (at least on my end :D)

**Comment by odow** [comment]
Hmm. I'll take a deeper look.
