### ISSUE TITLE
julia 0.6.0 install Ipopt cannot connect to mumps dependency

### ISSUE THREAD

**Issue by dlc1994** [jump-dev/Ipopt.jl#344]
Hello I am trying to install Ipopt with julia 0.6.0
but when trying to download mumps it stuck by connection error
I found that mumps provide two links to download
http://mumps.enseeiht.fr/MUMPS_4.10.0.tar.gz and 
http://graal.ens-lyon.fr/MUMPS/MUMPS_4.10.0.tar.gz

the first one is deprecated but used in install Ipopt
how can I change the config or other way to solve it.

Thx

![image](https://user-images.githubusercontent.com/13445045/204182522-a3980650-5620-445e-b382-faf0a5bcff8b.png)

**Comment by odow** [comment]
Julia v0.6.0 is (very) old and unsupported. Please use at least Julia v1.6.

**Comment by odow** [comment]
@dlc1994 I'm going to close this as "won't-fix." 

Please use a supported version of Julia downloaded from https://julialang.org/downloads/. (At the time of writing, either v1.8.3 or v1.6.7.) The good news is that newer versions of Julia use a different system for distributing the binaries, so we'll never have this problem of links going stale on the internet.

If you have further questions, please post on our community forum: https://discourse.julialang.org/c/domain/opt/13
