### ISSUE TITLE
Get number of iterations after optimization

### ISSUE THREAD

**Issue by ojwoodford** [jump-dev/Ipopt.jl#388]
It would be great to have a way to retrieve the number of iterations that Ipopt performed during an optimization. This can be useful to understand whether a particular cost function is either slow to evaluate or slow to converge. It can also be used to have a more fine-grained comparison between optimizers.

**Comment by ojwoodford** [comment]
> Is this so you can compare with NNLS?
So I can compare with other solvers on non-linear least squares problems, yes.

I can see the number of iterations in the log. It's pretty comparable with other methods. It's always useful to see how much work a particular solver is able to do per _iteration_, whatever that happens to mean in the context of a particular solver.

**Comment by odow** [comment]
See https://github.com/jump-dev/Ipopt.jl/pull/389
