### ISSUE TITLE
MUMPS_seq_jll@5.6.2 is slower than MUMPS_seq_jll@5.6.1

### ISSUE THREAD

**Issue by DoctorDro** [jump-dev/Ipopt.jl#403]
Dear all,
this is very easy to verify. On a clean installation of Julia type:
```
pkg> add PowerModels Ipopt PGLib
julia> using Ipopt,PowerModels,PGLib
```
For more information on where the time is spent add a single line in the ipopt.opt file and save it:
```
print_timing_statistics       yes
```

```
julia> solve_ac_opf(pglib(find_pglib_case("3012")[1]), Ipopt.Optimizer)
pkg> remove Ipopt
pkg> add Ipopt@1.5.1
```
Close and restart Julia for the changes to be applied and then try to solve the same problem again 
```
julia> using Ipopt,PowerModels,PGLib
julia> solve_ac_opf(pglib(find_pglib_case("3012")[1]), Ipopt.Optimizer)
```

**Comment by odow** [comment]
> Also, what is the output of versioninfo() and ] st -m

Can you provide this? How did you install Julia?

Since the time is dominated by the linear system solve, there's not much to fix on our end. The traces are not identical, so it isn't surprising that the runtimes might differ. This could just be luck, or some small change in numerical handling in MUMPS, or really anything.

You could try a different linear solver:

 * https://github.com/jump-dev/Ipopt.jl?tab=readme-ov-file#linear-solvers

Or swap the BLAS library:

 * https://github.com/jump-dev/Ipopt.jl?tab=readme-ov-file#blas-and-lapack

**Comment by odow** [comment]
More or less exactly the same timing:
```Julia
julia> LinearAlgebra.BLAS.lbt_get_config()
LinearAlgebra.BLAS.LBTConfig
Libraries: 
├ [ LP64] Accelerate
└ [ILP64] Accelerate
```

1.6.0

```
 StdAugSystemSolverMultiSolve.......:     10.598 (sys:      1.262 wall:      9.638)
```

1.5.1

```
 StdAugSystemSolverMultiSolve.......:      4.770 (sys:      0.539 wall:      5.338)
```

**Comment by amontoison** [comment]
I added some OpenMP flags with MUMPS 5.6.2.
It could be related to that.
I will try to recompile locally MUMPS with BinaryBuilder.jl asap.

**Comment by amontoison** [comment]
Do you compile MUMPS with -fopenmp?

SPRAL was developed by Jonathan Hogg, but he left the HSL team 10 years ago.
Nobody continued the development of SPRAL after.
He was the only expert in C++ / CUDA kernels, everybody else is doing Fortran.

Yes, HSL is more efficient and easy to use.
I'm quite happy that they accepted the collaboration for libHSL / HSL_jll.jl! :smiley:

**Comment by amontoison** [comment]
Thanks @DoctorDro! I recompile MUMPS with Yggdrasil now.

**Comment by odow** [comment]
Very weird. Thanks for digging deep into this @DoctorDro

**Comment by amontoison** [comment]
@DoctorDro
Do you see the same problem with the parallel version of MUMPS?
When I compiled MUMPS 5.6.2, I added `fopenmp` for `MUMPS_seq_jll` and `MUMPS_jll`.

**Comment by amontoison** [comment]
@DoctorDro
The release 1.6.1 of Ipopt.jl should fix your problem.
I recompiled `MUMPS_seq_jll` without OpenMP.
Then I upgraded `Ipopt_jll` for the version 3.14.14 with the updated dependencies (MUMPS / SPRAL).
