### ISSUE TITLE
BLIS for Ipopt.jl

### ISSUE THREAD

**Issue by stumarcus314** [jump-dev/Ipopt.jl#412]
In the Ipopt.jl README in the Section "BLAS and LAPACK" (https://github.com/jump-dev/Ipopt.jl#blas-and-lapack), you can also mention BLIS as an alternative to OpenBLAS (the default), Intel MKL, and Apple Accelerate. BLISBLAS.jl is a Julia package that uses BLIS for Julia's underlying BLAS and is compatible with LBT.

"Using LBT, we can also switch dynamically to other BLAS backends such as Intel MKL and Apple Accelerate."
->
"Using LBT, we can also switch dynamically to other BLAS backends such as Intel MKL, BLIS, and Apple Accelerate."

BLIS
If you have BLISBLAS.jl (https://github.com/JuliaLinearAlgebra/BLISBLAS.jl) installed, switch to BLIS by adding `using BLISBLAS` to your code:

```julia
using BLISBLAS  # Replace OpenBLAS BLAS functionality by BLIS. OpenBLAS is still used for LAPACK functionality.
using Ipopt
```

**Comment by amontoison** [comment]
BLISBLAS.jl only loads an ILP64 BLAS.
We need an LP64 BLAS / LAPACK for Ipopt and the dependencies.
Note that blis32_jll.jl must be combined with LAPACK32_jll.jl if we want to replace OpenBLAS32_jll.jl, MKL.jl or AppleAccelerate.jl.

**Comment by amontoison** [comment]
I aldo wanted to add a comment about sequential BLAS / LAPACK for MA86, MA87, MA97. They already use parallelism within the linear solver so we should not oversubscribe the threads with a multithreaded BLAS / LAPACK.

I will open a PR.
