### ISSUE TITLE
Segmentation fault during precompilation

### ISSUE THREAD

**Issue by Narcha** [jump-dev/Ipopt.jl#419]
On a fresh julia installation, I tried to install `Ipopt@1.6.3` but was met with a segmentation fault during precompilation.
<details><summary>Full error</summary>
<p>

```
ERROR: The following 1 direct dependency failed to precompile:

Ipopt [b6b21f68-93f8-5de0-b562-5493be1d77c9]

Failed to precompile Ipopt [b6b21f68-93f8-5de0-b562-5493be1d77c9] to "/home/***/.julia/compiled/v1.10/Ipopt/jl_Y0ERdX".
[21384] signal (11.1): Segmentation fault
in expression starting at /home/***/.julia/packages/Ipopt/bqp63/src/Ipopt.jl:40
dcopy_k_ZEN at /usr/bin/../lib/julia/../libopenblas64_.so (unknown line)
Allocations: 6365741 (Pool: 6361260; Big: 4481); GC: 1
```

The `libopenblas64_.so` mentioned in the error is a link to the following file:
`/usr/lib/libopenblas_64.so.0.3: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=81b85054d6d90ada35f16102f2e76028dfab864e, stripped
`
</p>
</details>

Weirdly enough, I "fixed" this error by installing `Ipopt@1.0`, which went fine, and then installing version 1.6.3 again.

<details><summary>System info</summary>
<p>

OS: Arch Linux
Julia version: 1.10.4
Installation method: distro repos (package `julia`)

</p>
</details>

**Comment by odow** [comment]
Please see the `Installation` section of https://wiki.archlinux.org/title/Julia

Installing the `julia` package is *not* officially supported.

Please install an official version of Julia: https://julialang.org/downloads/
