### ISSUE TITLE
Check feasibility after a restoration failure?

### ISSUE THREAD

**Issue by Robbybp** [jump-dev/Ipopt.jl#436]
One of my pet peeves with Ipopt is that it returns a `Restoration_Failed` status code even when it fails at a feasible or almost feasible point. In many applications and algorithms, a feasible solution is fine, and `Restoration_Failed` makes it seem like something is seriously wrong with the termination point. I encounter this often enough that I'd like to do something about it.

IMO Ipopt should use the `Feasible_Point_Found` status in these cases (or a similar status for "acceptably feasible"). Barring that, we could handle "(almost) feasible restoration failures" in this interface. My proposal would be to check primal feasibility if we encounter a restoration failure and return `MOI.LOCALLY_SOLVED`, `MOI.ALMOST_LOCALLY_SOLVED`, or `MOI.LOCALLY_INFEASIBLE` as appropriate.

**Comment by odow** [comment]
Closed by #435
