### ISSUE TITLE
distribute with MKL?

### ISSUE THREAD

**Issue by mlubin** [jump-dev/Ipopt.jl#6]
@ViralBShah mentioned in JuliaLang/julia#4272 that julia has a license to redistribute MKL. Could we use this for the Ipopt binaries? This should give much better default performance than with MUMPS.

@tkelman

**Comment by odow** [comment]
A potential route forward for this is to use `IpoptMKL_jll`, https://github.com/JuliaPackaging/Yggdrasil/pull/1031, but it's still a WIP.
