### ISSUE TITLE
How to check memory usage

### ISSUE THREAD

**Issue by mes9** [jump-dev/Ipopt.jl#69]
I'm experimenting with my model, and I want to know if my changes are helping or hurting the memory consumption. I have been using the @time to see the memory usage, but I do not know if that is the best method.

I also switched to the limited-memory hessian approximation and did not see any reduction in memory size with the @time macro, which surprised me. My problem is large, so memory is an issue

**Comment by mlubin** [comment]
Very few people read the Ipopt-Julia wrapper issues. I'd recommend the [Ipopt discussion list](http://list.coin-or.org/mailman/listinfo/ipopt).

**Comment by tkelman** [comment]
that's not a very active mailing list either, and people there won't know how to measure memory use in Julia.

**Comment by zhangxz1123** [comment]
Any update on this question?

**Comment by odow** [comment]
Closing as stale, and because this isn't specific to Ipopt.jl. There may be Julia tools to measure memory usage of `ccall`s that I'm unaware of, otherwise you could use standard OS tools to measure the memory usage of a process.
