### ISSUE TITLE
Ipopt installation fails behind a firewall

### ISSUE THREAD

**Issue by montyvesselinov** [jump-dev/Ipopt.jl#78]
The build.jl script fails behind a firewall (when the required resources cannot be accessed). It will be nice if the required resources (the tgz files) can be be placed in a directory from which the installation can be performed. Similar to `downloads/Ipopt-3.12.1.tgz`.

**Comment by odow** [comment]
I realize this is pretty old, but you should be able to do this with a custom installation: https://github.com/jump-dev/Ipopt.jl/tree/od/pardiso#custom-installation

**Comment by odow** [comment]
Closed by #236. There are now better instructions for how to use a custom installation of Ipopt.
